# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    environment: dev

    steps:
    - uses: actions/checkout@v3

    - name: Create .env.dev
      run: |
        echo "
        API_URL= ${{ secrets.API_URL }}
        CLIENT_BASEURL= ${{ secrets.CLIENT_BASEURL }}
        # Google
        GOOGLE_GSI_SRC= ${{ secrets.GOOGLE_GSI_SRC }}
        GOOGLE_GSI_CLIENT_ID= ${{ secrets.GOOGLE_GSI_CLIENT_ID }}
        # JEST
        JEST_USER_NAME= ${{ secrets.JEST_USER_NAME }}
        JEST_USER_EMAIL= ${{ secrets.JEST_USER_EMAIL }}
        JEST_USER_PASSWORD= ${{ secrets.JEST_USER_PASSWORD }}
        JEST_USER_PASSWORD_HINT= ${{ secrets.JEST_USER_PASSWORD_HINT }}
        JEST_USER_GENDER= ${{ secrets.JEST_USER_GENDER }}
        JEST_USER_PHONE= ${{ secrets.JEST_USER_PHONE }}
        JEST_USER_BIRTHDAY= ${{ secrets.JEST_USER_BIRTHDAY }}
        JEST_USER_NEW_EMAIL= ${{ secrets.JEST_USER_NEW_EMAIL }}
        JEST_USER_NEW_NAME= ${{ secrets.JEST_USER_NEW_NAME }}
        JEST_USER_NEW_PASSWORD= ${{ secrets.JEST_USER_NEW_PASSWORD }}
        JEST_USER_NEW_GENDER= ${{ secrets.JEST_USER_NEW_GENDER }}
        JEST_USER_NEW_PHONE= ${{ secrets.JEST_USER_NEW_PHONE }}
        JEST_USER_NEW_BIRTHDAY= ${{ secrets.JEST_USER_NEW_BIRTHDAY }}
        " > .env.dev
        ls -al
        cat .env.dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test-ci
